---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: omnios-151008f
    driver_config:
      box: omnios-r151008f
      box_url: http://omnios.omniti.com/media/OmniOS_r151008f-r1.box

suites:
  - name: default
    run_list:
      - recipe[motd::default]
    attributes:
